kind: Secret
apiVersion: v1
metadata:
  name: html-openshift-app-github
  labels:
    app: html-openshift-app
    app.kubernetes.io/part-of: html-openshift-app
data:
  username: Y2hpbGxpdmlu
  password: VmpWajIwMDg/
type: kubernetes.io/basic-auth

