kind: Secret
apiVersion: v1
metadata:
  name: html-openshift-app-github
  labels:
    app: html-openshift-app
    app.kubernetes.io/part-of: html-openshift-app
data:
  username: Ym93bGlndGg=
  password: Z2hwX3pXYVBVMVN3VFNHZmJNNUhRNVVzVnZmUjV5Y1ZEYTNGV2xOMA==
type: kubernetes.io/basic-auth
